name: demo_todos_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^3.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.17.0
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  retrofit: ^3.3.1
  sqflite: ^2.2.2
  sqflite_common_ffi: ^2.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
